import {useEffect,useState} from "react";
import {supabase} from "./lib/supabase";
import {ArrowRight,CheckCircle2,Eye,EyeOff,LockKeyhole,Mail,ShieldCheck} from "lucide-react";
type View="landing"|"login"|"forgot"|"reset"|"dashboard";

export default function App(){
 const [view,setView]=useState<View>("landing"),[email,setEmail]=useState("utulu.augustine@gmail.com"),[password,setPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[user,setUser]=useState<any>(null);
 const pct=73,target=200,reached=146,complete=pct>=100;
 useEffect(()=>{(async()=>{const h=new URLSearchParams(location.hash.replace(/^#/,""));if(h.get("access_token")&&h.get("type")==="recovery"){setView("reset");setMessage("Your reset link is valid. Choose a new password.");return}const {data}=await supabase.auth.getSession();if(data.session){setUser(data.session.user);setView("dashboard")}})();const {data}=supabase.auth.onAuthStateChange((_e,s)=>{if(s)setUser(s.user)});return()=>data.subscription.unsubscribe()},[]);
 const run=async(fn:any)=>{setLoading(true);setError("");setMessage("");try{const r=await fn();if(r.error)setError(r.error.message);return r}finally{setLoading(false)}};
 const login=async()=>{const r=await run(()=>supabase.auth.signInWithPassword({email,password}));if(!r.error)setView("dashboard")};
 const forgot=async()=>{const r=await run(()=>supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin}));if(!r.error)setMessage("If this email belongs to an account, a password-reset email has been sent.")};
 const reset=async()=>{if(newPassword.length<8){setError("Password must be at least 8 characters.");return}const r=await run(()=>supabase.auth.updateUser({password:newPassword}));if(!r.error){history.replaceState({},"",location.pathname);await supabase.auth.signOut();setMessage("Your password has been updated.");setView("login")}};
 const logout=async()=>{await supabase.auth.signOut();setUser(null);setPassword("");setView("landing")};
 const Field=({label,value,onChange,type="text",icon}:any)=><label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><div className="relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">{icon}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-slate-200 px-11 py-3.5 outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100"/></div></label>;
 const Card=({title,sub,children}:any)=><div className="min-h-screen bg-slate-50 px-5 py-10"><div className="mx-auto max-w-md"><button onClick={()=>setView("landing")} className="mb-8 font-black text-emerald-700">IB PROGRAM</button><div className="rounded-3xl bg-white p-6 shadow-xl ring-1 ring-slate-200 sm:p-8"><div className="mb-7"><div className="mb-4 inline-flex rounded-2xl bg-emerald-50 p-3 text-emerald-700"><LockKeyhole/></div><h1 className="text-2xl font-black">{title}</h1><p className="mt-2 text-sm text-slate-500">{sub}</p></div>{error&&<div className="mb-4 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="mb-4 rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}{children}</div></div></div>;
 if(view==="dashboard"&&user)return <main className="min-h-screen bg-slate-50 text-slate-900"><nav className="border-b border-emerald-100 bg-white"><div className="mx-auto flex max-w-6xl justify-between px-5 py-4"><b className="text-emerald-700">IB PROGRAM</b><button onClick={logout} className="rounded-xl border border-emerald-200 px-4 py-2 text-sm font-semibold text-emerald-700">Log out</button></div></nav><section className="mx-auto max-w-6xl px-5 py-10"><p className="text-sm font-semibold text-emerald-700">Account dashboard</p><h1 className="mt-2 text-3xl font-black">Welcome back</h1><div className="mt-7 grid gap-5 md:grid-cols-3"><div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-emerald-100 md:col-span-2"><div className="flex gap-3"><ShieldCheck className="text-emerald-700"/><div><p className="text-sm text-slate-500">Account holder</p><b>{user.user_metadata?.name||"Augustine Utulu"}</b><p className="text-sm text-slate-500">{user.email}</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-5"><p className="text-sm text-slate-500">Account status</p><b className="mt-1 flex gap-2 text-emerald-700"><CheckCircle2 size={18}/>Active</b></div><div className="rounded-2xl bg-emerald-700 p-5 text-white"><p className="text-sm text-emerald-100">Progress reached</p><b className="text-3xl">${reached}</b><p className="text-xs text-emerald-100">{pct}% of ${target} target</p></div></div><div className="mt-5 rounded-3xl border border-emerald-100 p-6"><div className="flex justify-between"><div><p className="font-semibold text-emerald-700">Program roadmap</p><b className="text-2xl">${reached} <span className="text-base text-slate-400">/ ${target}</span></b></div><b className="text-2xl text-emerald-700">{pct}%</b></div><div className="mt-4 h-3 rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{width:`${pct}%`}}/></div><div className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><p className="text-slate-400">Starting date</p><b>12 May 2026</b></div><div className="sm:text-right"><p className="text-slate-400">Expected completion</p><b>21 October 2026</b></div></div></div></div><div className="rounded-3xl bg-emerald-800 p-6 text-white"><p className="text-emerald-100">Program access</p><h2 className="mt-2 text-2xl font-black">Independent access</h2><div className="mt-8 border-t border-white/10 pt-5"><p>Withdrawal</p><button disabled={!complete} className="mt-3 w-full rounded-2xl bg-white/10 px-4 py-3 font-bold disabled:opacity-50">{complete?"Withdrawal available":"Withdrawal locked"}</button><p className="mt-2 text-xs text-slate-400">Available only when progress reaches 100%.</p></div></div></div></section></main>;
 if(view==="login")return <Card title="Welcome back" sub="Sign in securely to your IB Program account."><div className="space-y-5"><Field label="Email address" value={email} onChange={setEmail} type="email" icon={<Mail size={18}/>}/><div className="relative"><Field label="Password" value={password} onChange={setPassword} type={show?"text":"password"} icon={<LockKeyhole size={18}/>}/><button onClick={()=>setShow(!show)} className="absolute right-3 top-9 p-2 text-slate-400">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><button disabled={loading} onClick={login} className="flex w-full justify-center gap-2 rounded-2xl bg-emerald-700 py-3.5 font-bold text-white">{loading?"Signing in...":"Sign in"} <ArrowRight size={18}/></button><button onClick={()=>setView("forgot")} className="w-full text-sm font-semibold text-emerald-700">Forgot password?</button></div></Card>;
 if(view==="forgot")return <Card title="Reset your password" sub="Enter the email connected to your account."><div className="space-y-5"><Field label="Email address" value={email} onChange={setEmail} type="email" icon={<Mail size={18}/>}/><button disabled={loading} onClick={forgot} className="w-full rounded-2xl bg-emerald-700 py-3.5 font-bold text-white">{loading?"Sending...":"Send reset email"}</button><button onClick={()=>setView("login")} className="w-full text-sm text-slate-500">Back to sign in</button></div></Card>;
 if(view==="reset")return <Card title="Create a new password" sub="Choose a strong password."><div className="space-y-5"><Field label="New password" value={newPassword} onChange={setNewPassword} type="password" icon={<LockKeyhole size={18}/>}/><button disabled={loading} onClick={reset} className="w-full rounded-2xl bg-emerald-700 py-3.5 font-bold text-white">{loading?"Updating...":"Update password"}</button></div></Card>;
 return <main className="min-h-screen bg-slate-950 text-white"><nav className="mx-auto flex max-w-6xl justify-between px-5 py-5"><b className="text-emerald-300">IB PROGRAM</b><button onClick={()=>setView("login")} className="rounded-xl border border-white/15 px-4 py-2 text-sm font-bold">Sign in</button></nav><section className="mx-auto grid min-h-[calc(100vh-80px)] max-w-6xl items-center gap-12 px-5 py-12 lg:grid-cols-[1.15fr_.85fr]"><div><div className="mb-5 inline-flex gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs font-bold text-emerald-300"><ShieldCheck size={15}/>Secure account access</div><h1 className="text-5xl font-black leading-tight sm:text-6xl">Your IB Program access, <span className="text-emerald-400">in one place.</span></h1><p className="mt-6 max-w-xl text-slate-300">Secure account access, password recovery and a private program dashboard in one place.</p><button onClick={()=>setView("login")} className="mt-8 inline-flex gap-2 rounded-2xl bg-emerald-500 px-6 py-3.5 font-black text-slate-950">Access account <ArrowRight size={18}/></button></div><div className="rounded-[2rem] border border-white/10 bg-white/[.06] p-6"><div className="rounded-3xl border-t-4 border-emerald-600 bg-white p-6 text-slate-900"><p className="font-semibold text-emerald-700">Secure portal</p><h2 className="mt-3 text-2xl font-black">Private account access</h2><p className="mt-3 text-sm text-slate-500">Sign in to view your personal account information and program details.</p><div className="mt-6 flex gap-3 rounded-2xl bg-emerald-50 p-4"><ShieldCheck className="text-emerald-700"/><div><b className="text-sm">Protected dashboard</b><p className="text-xs text-slate-500">Account details are available after sign in.</p></div></div></div></div></section></main>;
}